### ISSUE TITLE
Write logs to stderr

### ISSUE THREAD

**Issue by dadav** [alcideio/rbac-tool#106]
**What would you like to be added**:

Make it possible to write the logs to stderr.

**Why is this needed**:

The logs are not separate from the outfile data. So to make the following command work, some filtering is required:
```sh
kubectl rbac-tool viz --outformat dot --outfile - | dot -Tpng >foo.png
```

**Comment by gadinaor-r7** [comment]
@dadav - thanks for the PR - i'll take a look later today
