### ISSUE TITLE
podSecurityPolicy has been removed

### ISSUE THREAD

**Issue by blevz** [alcideio/rbac-tool#110]
**What happened**:
Rbac-tool fails to build for modern k8s versions bc pod security policy has been deprecated and removed from the k8s library 

**What you expected to happen**:
Rbac-tool compiles when using support k8s library version

**How to reproduce it (as minimally and precisely as possible)**:
Upgrade k8s client to v 1.28 and try to build 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or configuration:
- Install tools:
- Others:

**Comment by gadinaor-r7** [comment]
@blevz - thanks - final removal will take place once dependencies are updated to a later k8s version
