### ISSUE TITLE
Mistake in docs? (visualize --help)

### ISSUE THREAD

**Issue by sudoleg** [alcideio/rbac-tool#115]
https://github.com/alcideio/rbac-tool/blob/2833fda6a5f9432e4eb6f02167b59322c5b84163/cmd/visualize_cmd.go#L79

Hello folks, to my understanding, the `--exclude-namespaces` option exculdes namespaces from visualization. However, the output of the `visualuze --help` command says that it's a "Comma-delimited list of namespaces to **include** in the visualization (default "kube-system")". If it's indeed a mistake, I would be happy to submit a PR for fixing it :)

**Comment by gadinaor-r7** [comment]
@sudoleg - thanks - happy to take a PR to fix the typo J

**Comment by sudoleg** [comment]
@gadinaor-r7 done :) https://github.com/alcideio/rbac-tool/pull/116
