### ISSUE TITLE
v0.9.1 renders dot but names the output .html

### ISSUE THREAD

**Issue by alesti** [alcideio/rbac-tool#20]
**What happened**:
```
[130] % rbac-tool viz --outformat dot   
[alcide-rbactool] Namespaces included '*'
[alcide-rbactool] Namespaces excluded 'kube-system'
[alcide-rbactool] Connecting to cluster ''
[alcide-rbactool] Generating Graph and Saving as 'rbac.html'

[0] % head -2 rbac.html                                                                                   
digraph  {
        subgraph cluster_s296 {
```

**What you expected to happen**:
I expect to name a dot file `.dot` :-D

Looks like connected to [issue 8](https://github.com/alcideio/rbac-tool/issues/8)

**How to reproduce it (as minimally and precisely as possible)**:
`rbac-tool viz --outformat dot`

**Anything else we need to know?**:

Dot itself renders the file fine, it looks just like a file nameing error.

It would be also nice to see the used version at least in `-h`

**Environment**:
- Kubernetes version (use `kubectl version`): irrelevant, happens with 1.15.11 and also 1.18.x

**Comment by gadinaor** [comment]
Fixed in v0.10.0
