### ISSUE TITLE
Release an ARM binary as well

### ISSUE THREAD

**Issue by iuliancristea** [alcideio/rbac-tool#25]
**What would you like to be added**:
@gadinaor @austinpray-mixpanel, could ARM releases be made available for the latest version? It should be a quick GoReleaser config change.

**Comment by gadinaor** [comment]
@iuliancristea  - let me know if the additional artifacts address your needs

**Comment by iuliancristea** [comment]
> @iuliancristea - let me know if the additional artifacts address your needs

Yes, @gadinaor, thank you!
