### ISSUE TITLE
sha256 mismatch

### ISSUE THREAD

**Issue by mbentley** [alcideio/rbac-tool#30]
**What happened**:

Using the install via curl option, it fails to validate the checksum for `rbac-tool_v1.1.1_linux_amd64`:

```
$ curl https://raw.githubusercontent.com/alcideio/rbac-tool/master/download.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9331  100  9331    0     0  64798      0 --:--:-- --:--:-- --:--:-- 64798
alcideio/rbac-tool info checking GitHub for latest tag
alcideio/rbac-tool info found version: 1.1.1 for v1.1.1/linux/amd64
alcideio/rbac-tool err hash_sha256_verify checksum for '/tmp/tmp.rSW6XMKhUl/rbac-tool_v1.1.1_linux_amd64' did not verify 6916b6f609b027ccd7d6573a40f62492a84bc7445592805d6d3fc838f3e34dc4
ecdc8b365b8f9bb4303d194e777a9e7fdf3376158e3a2fb78cf7425007118a1d vs 6916b6f609b027ccd7d6573a40f62492a84bc7445592805d6d3fc838f3e34dc4
```

**What you expected to happen**:
The binary should match the checksum

**How to reproduce it (as minimally and precisely as possible)**:
See above

**Anything else we need to know?**:
Probably not.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or configuration:
- Install tools:
- Others:

**Comment by gadinaor** [comment]
@mbentley - thanks - looking into this

**Comment by gadinaor** [comment]
@mbentley - the download was fixed to match the release artifacts  - should be working now
