### ISSUE TITLE
rbac tool support for Mac M1

### ISSUE THREAD

**Issue by frittenlab** [alcideio/rbac-tool#32]
I tried to install the plugin today and I got this error message on my M1 Mac

```
kubectl krew install rbac-tool
Updated the local copy of plugin index.
Installing plugin: rbac-tool
W0719 13:57:13.752477   51960 install.go:164] failed to install plugin "rbac-tool": plugin "rbac-tool" does not offer installation for this platform
F0719 13:57:13.752552   51960 root.go:79] failed to install some plugins: [rbac-tool]: plugin "rbac-tool" does not offer installation for this platform
```

It would be great if the rbac tool would support the M1 Mac Arm64 platform.

**Comment by gadinaor** [comment]
#33

**Comment by gadinaor** [comment]
@frittenlab Mac M1 support should be as soon as kubernetes-sigs/krew-index#1417 is merged.

**Comment by gadinaor** [comment]
@frittenlab - looks like we should be good there ... can you give it another shot and let us know if there are any issues?
