### ISSUE TITLE
rbac-tool crashes on Mac M1 (ARM)

### ISSUE THREAD

**Issue by tunguyen9889** [alcideio/rbac-tool#34]
**What happened**:
I installed `rbac-tool` using both `krew` and binary download, both failed with same error:

```
➜  ~ rbac-tool who-can
[1]    86368 killed     rbac-tool who-can
➜  ~ kubectl rbac-tool who-can
[1]    86841 killed     kubectl rbac-tool who-can
➜  ~ kubectl rbac-tool --help
[1]    86883 killed     kubectl rbac-tool --help
➜  ~ kubectl rbac-tool --help
[1]    86922 killed     kubectl rbac-tool --help
➜  ~ rbac-tool who-can
[1]    86936 killed     rbac-tool who-can
```
**What you expected to happen**:
`rbac-tool` should run successfully.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
➜  ~ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:58:09Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:59:07Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or configuration:
- Install tools: `krew` and binary download.
- Others:

**Comment by gadinaor-r7** [comment]
macOS on arm64 [requires code signing](https://developer.apple.com/forums/thread/669188) - this is captured here - https://github.com/golang/go/issues/42684

Right now cross-platform builds are running on a linux host, which prevents us from running `codesign `.

Potential workaround:

```
Unable to sign the macOS executable on non-macOS host
Due to the mandatory code signing requirement, before the
executable is distributed to end users, it must be signed with
the "codesign" utility of macOS, otherwise, it will be immediately
killed by kernel on launch. An ad-hoc signature is sufficient.
To do that, "codesign --sign - <executable>" on a Mac.
```

**Comment by tunguyen9889** [comment]
Hi,

I'm trying to sign the binary, but got this error (Xcode was installed already):

```
➜  ~ cd .krew/store/rbac-tool/v1.2.0
➜  v1.2.0 codesign --force --deep --sign - rbac-tool
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate: object: /Users/james/.krew/store/rbac-tool/v1.2.0/rbac-tool malformed object (load command 3 cmdsize not a multiple of 8)
rbac-tool: the codesign_allocate helper tool cannot be found or used
```

**Comment by gadinaor-r7** [comment]
@tunguyen9889 ... still need to figure this out

**Comment by ciiiii** [comment]
> The test release in available in [v1.6.1](https://github.com/ciiiii/rbac-tool/releases/tag/v1.6.1), test passed on my m1 Mac.
> 
> ```shell
> wget https://github.com/ciiiii/rbac-tool/releases/download/v1.6.1/rbac-tool_v1.6.1_darwin_arm64.tar.gz
> 
> tar -xzvf rbac-tool_v1.6.1_darwin_arm64.tar.gz
> 
> ./rbac-tool
> ```
> 
> Maybe you should allow this in `Setting Preferences > Security&Privacy`.
@tunguyen9889, You can test this.

**Comment by gadinaor** [comment]
@ciiiii was able to track down an issue with UPX 3.96 on Darwin ARM64 [here ](https://github.com/upx/upx/issues/446)

**Comment by tunguyen9889** [comment]
Hi @ciiiii and @gadinaor, new release runs well on Darwin ARM64. Appreciate your works!

**Comment by ciiiii** [comment]
> Hi @ciiiii and @gadinaor, new release runs well on Darwin ARM64. Appreciate your works!

You're welcome.
