### ISSUE TITLE
Add subresources to generate 

### ISSUE THREAD

**Issue by MaxRink** [alcideio/rbac-tool#48]
**What would you like to be added**:
Add the option to add subcommands like `pods/exec` into generated RBAC files
**Why is this needed**:
Sometimes you want to give people more granular permissions on certain things and having a complete list on all avaiable subcommands in your rbac so you can easily do so would be nice

**Comment by gadinaor-r7** [comment]
@MaxRink thanks for adding this feature request.

Could you maybe give couple of examples of how you'd want to see that CLI to look like?

**Comment by gadinaor** [comment]
fyi @MaxRink - v1.10 adds the show command which basically includes sub-resources and the relevant verbs in a generated role.

This is of course kubernetes version (and cluster) specific.

**Comment by MaxRink** [comment]
@gadinaor that looks pretty much like what i was looking for :)
