### ISSUE TITLE
analyze: Failed to evaluate rules - no such key: allowedTo

### ISSUE THREAD

**Issue by ryanbrainard** [alcideio/rbac-tool#49]
**What happened**:

I'm trying to run `kubectl rbac-tool analyze`, but it is failing on all the rules that have `allowedTo` in them (which is all of the default ones).

**What you expected to happen**:

I expect it to analyze without erroring.

**How to reproduce it (as minimally and precisely as possible)**:

```
$ kubectl rbac-tool analyze       
E0126 12:46:45.944039   30783 analysis.go:316] Failed to evaluate rule 'Secret Readers' - no such key: allowedTo
E0126 12:46:45.947001   30783 analysis.go:316] Failed to evaluate rule 'Workload Creators & Editors' - no such key: allowedTo
E0126 12:46:45.949413   30783 analysis.go:316] Failed to evaluate rule 'Identify Privileges Escalators - via impersonate' - no such key: allowedTo
E0126 12:46:45.952296   30783 analysis.go:316] Failed to evaluate rule 'Identify Privileges Escalators - via bind or escalate' - no such key: allowedTo
E0126 12:46:45.957127   30783 analysis.go:316] Failed to evaluate rule 'Storage & Data - Manipulate Cluster Shared Resources' - no such key: allowedTo
E0126 12:46:45.960619   30783 analysis.go:316] Failed to evaluate rule 'Networking - Manipulate Networking and Network Access related resources' - no such key: allowedTo
E0126 12:46:45.963584   30783 analysis.go:316] Failed to evaluate rule 'Installing or Modifying Admission Controllers' - no such key: allowedTo
E0126 12:46:45.967046   30783 analysis.go:316] Failed to evaluate rule 'Installing or Modifying Cluster Extensions (CRDs)' - no such key: allowedTo
E0126 12:46:45.973053   30783 analysis.go:316] Failed to evaluate rule 'Open Policy Agent (OPA) GateKeeper Administration' - no such key: allowedTo
AnalysisConfigInfo:
  Description: Rapid7 InsightCloudSec default RBAC analysis rules
  Name: InsightCloudSec
  Uuid: 9371719c-1031-468c-91ed-576fdc9e9f59
CreatedOn: "2022-01-26T12:46:45+09:00"
Findings: []
Stats:
  ExclusionCount: 0
  RuleCount: 9
```

**Anything else we need to know?**:

I also tried it on a vanilla 1.22 cluster and it worked, so thinking this might be something with the cluster version. I'm not aware of a change to RBAC models in those versions that would cause this, but of course I might have missed something.
 
**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:33:37Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.11-eks-f17b81", GitCommit:"f17b810c9e5a82200d28b6210b458497ddfcf31b", GitTreeState:"clean", BuildDate:"2021-10-15T21:46:21Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.20) exceeds the supported minor version skew of +/-1
```

- Cloud provider or configuration:
AWS/EKS

**Comment by gadinaor-r7** [comment]
@ryanbrainard - thanks for this.

On your EKS environment - what permissions are you running with ? I suspect that when running against your 1.22 vanilla cluster - you have admin level permissions and with EKS that's not the case .

Regardless of that - the error messages can be improved

**Comment by gadinaor-r7** [comment]
@ryanbrainard v1.6.3 has a fix for those error messages.

closing this issue for now.

**Comment by ryanbrainard** [comment]
> @ryanbrainard - thanks for this.
> 
> On your EKS environment - what permissions are you running with ? I suspect that when running against your 1.22 vanilla cluster - you have admin level permissions and with EKS that's not the case .
> 
> Regardless of that - the error messages can be improved

@gadinaor-r7 I'm running as a full admin on the EKS cluster:

```
$ kubectl auth can-i '*' '*'
yes
```

With that said, I pulled down your fix, and it seems to work now. Thanks for the quick turnaround.
