### ISSUE TITLE
no access to psp == viz fail even though showpsp=false passed

### ISSUE THREAD

**Issue by dee0sap** [alcideio/rbac-tool#52]
**What happened**:
I don't have access to psp.   I ran viz with showpsp=false and still it failed with error about my lack of access to psp

**What you expected to happen**:
viz should work as normal for above scenario

**How to reproduce it (as minimally and precisely as possible)**:
Use viz when you're user doesn't have psp access

**Anything else we need to know?**:
PR with fix here https://github.com/alcideio/rbac-tool/pull/51

**Environment**:
- Kubernetes version (use `kubectl version`): 1.23.0 client, 1.21.10 server
- Cloud provider or configuration: AWS and Azure
- Install tools:
- Others:

**Comment by gadinaor-r7** [comment]
Release v1.7.0 should address that as we are moving away from PSP
