### ISSUE TITLE
kubectl rbac-tool gen is written to stderr

### ISSUE THREAD

**Issue by kahirokunn** [alcideio/rbac-tool#67]
**What happened**:

I tried to redirect the file with the following command, but the result was displayed on the screen and test.yaml was empty.

```sh
kubectl rbac-tool gen --deny-resources=secrets. --allowed-verbs=get,list,watch > test.yaml
```

However, the following command works fine.

```sh
kubectl rbac-tool gen --deny-resources=secrets. --allowed-verbs=get,list,watch 2> test.yaml
```

I thought that outputting the result to stderr might be a bug, but there might be circumstances that I don't know about. Why is it being output to the error?

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or configuration:
- Install tools:
- Others:

**Comment by gadinaor** [comment]
@kahirokunn - thanks for submitting - this is indeed something that should be fixed.

If you'd like to PR a fix - we'd be happy to review - otherwise - we will fix it in one of the coming releases

**Comment by kahirokunn** [comment]
I love this tool and will try to fix it.

**Comment by gadinaor** [comment]
will be part of the next release

**Comment by kahirokunn** [comment]
Thx.
