### ISSUE TITLE
No visualization when run on openshift cluster

### ISSUE THREAD

**Issue by NotABugItsAFeature** [alcideio/rbac-tool#68]
**What happened**:
The page generated seems to have data however the data is not visualized. Only the Legend can be seen.

**What you expected to happen**:
Visualized rbac controls.

**How to reproduce it (as minimally and precisely as possible)**:
./bin/rbac-tool visualize

**Anything else we need to know?**:
 No.

**Environment**:
- Kubernetes version (use `kubectl version`):
Server Version: 4.10.42
Kubernetes Version: v1.23.12+8a6bfe4
- Cloud provider or configuration:
On-prem
- Install tools:
?
- Others:
?

**Comment by gadinaor** [comment]
@NotABugItsAFeature  - with which rbac permissions are you running with? do you have cluster read-only? or namespace read only?Are you able to run any of the other commands?

Try to use `kubectl auth can-i ...`

**Comment by NotABugItsAFeature** [comment]
> @NotABugItsAFeature - with which rbac permissions are you running? do you have cluster read-only? or namespace read only?Are you able to run any of the other commands?
> 
> Try to use `kubectl auth can-i ...`

I have the cluster-admin role.
If you can give a specific 'auth can-i' to check I can do that. But I'd have expected an error be thrown when the info is gathered.

The odd thing is that the file seems to have the data. It's 25megabytes in size.

**Comment by gadinaor** [comment]
@NotABugItsAFeature  - which browser do you use to open the file?
Can you share the generated file privately (to gadi_naor at rapid7 dot com)?

**Comment by NotABugItsAFeature** [comment]
I've tried both with Chrome and Firefox. I'll have a look to share the file with you.

**Comment by gadinaor-r7** [comment]
@NotABugItsAFeature - sent you an email . Indeed seems like we snagged a capacity limit when it comes to rendering large graphs.

As a potential work around - you can generate the graph from a namespace (or few of them) and hopefully escape that graphing library behavior.
