### ISSUE TITLE
Some resources are not covered by "show", but exist in cluster

### ISSUE THREAD

**Issue by MaxRink** [alcideio/rbac-tool#79]
**What happened**:
Currently some resources, like events.events.k8s.io or nodes.metrics.k8s.io down show ub in the "show" output, despite existing in cluster

**What you expected to happen**:
"show" includes those ApiGroups and resources
**How to reproduce it (as minimally and precisely as possible)**:
Have an plain upstream cluster for events.events.k8s.io, use the metrics-sever for metrics.k8s.io
**Anything else we need to know?**:
n/a
**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or configuration:
- Install tools:
- Others:

**Comment by gadinaor-r7** [comment]
Thanks for the fix !!!! and apologies for the infinite delay
