### ISSUE TITLE
ExclusionCount Stats without explaination

### ISSUE THREAD

**Issue by vozhang-wish** [alcideio/rbac-tool#93]
**What would you like to be added**:
Add reasons and detailed information of ExclusionCount if possible

**Why is this needed**:
get the ExclusionCount:  info. in Stats, but have no idea why and what. 
For Why, is it because i miss some of the permission? If yes, which permission in detail
For What, what exactly the exclusion is?

**Comment by gadinaor** [comment]
@vozhang-wish - HNY and thanks for submitting the enhancement request.

As a temporary workaround and until I am able to see what's the best way to convey a more detailed output - right now the debug log gives more details when exclusion counter is increased.

**Comment by gadinaor-r7** [comment]
@vozhang-wish - v1.16.0 includes #99 which should address this ask.
